"""add email_id

Revision ID: 24a71017d002
Revises: 539c2b7cea29
Create Date: 2022-04-01 17:33:11.169696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a71017d002'
down_revision = '539c2b7cea29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('email_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 'emails', ['email_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='unique')
    op.drop_column('emails', 'email_id')
    # ### end Alembic commands ###
