"""add idx in table email

Revision ID: 2fa9991194d9
Revises: 24a71017d002
Create Date: 2022-04-02 18:53:56.639984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa9991194d9'
down_revision = '24a71017d002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email_idx_for_need_to_process', 'emails', ['status', sa.text('timestamp ASC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_idx_for_need_to_process', table_name='emails')
    # ### end Alembic commands ###
