"""create table emails user_recipients email_histories

Revision ID: 6eb6b01abbb2
Revises: 
Create Date: 2022-04-01 00:33:00.958556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb6b01abbb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('email_subject', sa.String(length=100), nullable=False),
    sa.Column('email_content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SCHEDULED', 'PROCESSED', name='email_status_choices_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('user_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_id')
    )
    op.create_table('email_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('history_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PROCESS', 'SUCCCESS', 'FAIL', 'PENDING', 'SCHEDULED', name='email_history_status_choices_enum'), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('user_recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['user_recipient_id'], ['user_recipients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_histories')
    op.drop_table('user_recipients')
    op.drop_table('emails')
    # ### end Alembic commands ###
